"""One-time enrichment: adds latitude/longitude to each Andhra Pradesh entry
in last_known_prices.json, computed as the mean coordinate of all cleanly-
matched taluks (pincode_geo_reference.json, match_confidence == "matched")
that resolved to that district.

Only Andhra Pradesh entries can be enriched -- pincode_geo_reference.json is
built from all_ap_postoffices.xlsx, so no other state has geo data yet.
Entries for other states are left unchanged (no latitude/longitude fields).

last_known_prices.json is regenerated by the scheduled Agmarknet scraper, so
this enrichment does not persist automatically -- re-run this script after any
scrape refresh if the lat/long fields need to be restored.

CLI: python -m bot_processors.enrich_prices_with_geo
"""

import json
from collections import defaultdict
from pathlib import Path

from loguru import logger

_GEO_REFERENCE_PATH = Path(__file__).parent / "pincode_geo_reference.json"
_LAST_KNOWN_PATH = Path(__file__).parent / "last_known_prices.json"


def _district_centroids() -> dict[str, tuple[float, float]]:
    with open(_GEO_REFERENCE_PATH, encoding="utf-8") as f:
        geo_rows = json.load(f)

    coords_by_district: dict[str, list[tuple[float, float]]] = defaultdict(list)
    for row in geo_rows:
        if row["match_confidence"] != "matched":
            continue
        coords_by_district[row["matched_district"]].append((row["latitude"], row["longitude"]))

    centroids = {}
    for district, coords in coords_by_district.items():
        avg_lat = sum(c[0] for c in coords) / len(coords)
        avg_lon = sum(c[1] for c in coords) / len(coords)
        centroids[district] = (avg_lat, avg_lon)
    return centroids


def enrich() -> None:
    centroids = _district_centroids()
    logger.info(f"Built centroids for {len(centroids)} districts from clean-matched taluks")

    with open(_LAST_KNOWN_PATH, encoding="utf-8") as f:
        prices = json.load(f)

    updated = 0
    missing_districts = set()
    for entry in prices.values():
        if entry.get("state") != "Andhra Pradesh":
            continue
        centroid = centroids.get(entry["district"])
        if centroid is None:
            missing_districts.add(entry["district"])
            continue
        entry["latitude"], entry["longitude"] = centroid
        updated += 1

    with open(_LAST_KNOWN_PATH, "w", encoding="utf-8") as f:
        json.dump(prices, f, ensure_ascii=False, indent=2)

    logger.info(f"Added latitude/longitude to {updated} Andhra Pradesh price entries")
    if missing_districts:
        logger.warning(f"No geo data for districts: {sorted(missing_districts)}")


if __name__ == "__main__":
    enrich()
