"""One-time enrichment: adds latitude/longitude and the list of pincodes to
each Andhra Pradesh entry in last_known_prices.json, derived from all
cleanly-matched taluks (pincode_geo_reference.json, match_confidence ==
"matched") that resolved to that district. latitude/longitude are the mean
coordinate across those taluks; pincodes is the sorted list of unique
pincodes that fall in the district.

Only Andhra Pradesh entries can be enriched -- pincode_geo_reference.json is
built from all_ap_postoffices.xlsx, so no other state has geo data yet.
Entries for other states are left unchanged (no latitude/longitude/pincodes
fields).

last_known_prices.json is regenerated by the scheduled Agmarknet scraper, so
this enrichment does not persist automatically -- re-run this script after any
scrape refresh if these fields need to be restored.

CLI: python -m bot_processors.enrich_prices_with_geo
"""

import json
from collections import defaultdict
from pathlib import Path

from loguru import logger

_GEO_REFERENCE_PATH = Path(__file__).parent / "pincode_geo_reference.json"
_LAST_KNOWN_PATH = Path(__file__).parent / "last_known_prices.json"


def _district_geo() -> dict[str, dict]:
    with open(_GEO_REFERENCE_PATH, encoding="utf-8") as f:
        geo_rows = json.load(f)

    coords_by_district: dict[str, list[tuple[float, float]]] = defaultdict(list)
    pincodes_by_district: dict[str, set[str]] = defaultdict(set)
    for row in geo_rows:
        if row["match_confidence"] != "matched":
            continue
        district = row["matched_district"]
        coords_by_district[district].append((row["latitude"], row["longitude"]))
        pincodes_by_district[district].add(row["pincode"])

    geo_by_district = {}
    for district, coords in coords_by_district.items():
        avg_lat = sum(c[0] for c in coords) / len(coords)
        avg_lon = sum(c[1] for c in coords) / len(coords)
        geo_by_district[district] = {
            "latitude": avg_lat,
            "longitude": avg_lon,
            "pincodes": sorted(pincodes_by_district[district]),
        }
    return geo_by_district


def enrich() -> None:
    geo_by_district = _district_geo()
    logger.info(f"Built geo data for {len(geo_by_district)} districts from clean-matched taluks")

    with open(_LAST_KNOWN_PATH, encoding="utf-8") as f:
        prices = json.load(f)

    updated = 0
    missing_districts = set()
    for entry in prices.values():
        if entry.get("state") != "Andhra Pradesh":
            continue
        geo = geo_by_district.get(entry["district"])
        if geo is None:
            missing_districts.add(entry["district"])
            continue
        entry["latitude"] = geo["latitude"]
        entry["longitude"] = geo["longitude"]
        entry["pincodes"] = geo["pincodes"]
        updated += 1

    with open(_LAST_KNOWN_PATH, "w", encoding="utf-8") as f:
        json.dump(prices, f, ensure_ascii=False, indent=2)

    logger.info(f"Added latitude/longitude/pincodes to {updated} Andhra Pradesh price entries")
    if missing_districts:
        logger.warning(f"No geo data for districts: {sorted(missing_districts)}")


if __name__ == "__main__":
    enrich()
