"""Enriches last_known_prices.json with location data for each price entry.

For Andhra Pradesh / Telangana entries: a precise single `pincode` plus
`latitude`/`longitude` for the entry's own market yard, sourced from
market_yard_geo_reference.json (built from AP_Telangana_Market_Yards_filled.xlsx
-- confirmed live: 242 of 243 AP/TG entries match it exactly on
(state, district, market)). This supersedes an earlier version of this script
that attached the full list of every pincode in the district (from
pincode_geo_reference.json, the coarser postoffice-based pipeline) -- that
list didn't identify which pincode was actually near the market in question,
just every pincode anywhere in the district (up to 98 for one district).

Falls back to the district centroid (pincode_geo_reference.json) only for the
rare AP/TG market missing from market_yard_geo_reference.json, and adds no
fields for states outside AP/Telangana (no source data yet for the rest of
India).

last_known_prices.json is regenerated by the scheduled Agmarknet scraper, so
this enrichment does not persist automatically -- re-run this script after any
scrape refresh to restore these fields.

CLI: python -m bot_processors.enrich_prices_with_geo
"""

import json
from pathlib import Path

from loguru import logger

_MARKET_GEO_PATH = Path(__file__).parent / "market_yard_geo_reference.json"
_DISTRICT_GEO_PATH = Path(__file__).parent / "pincode_geo_reference.json"
_LAST_KNOWN_PATH = Path(__file__).parent / "last_known_prices.json"

_AP_TG_STATES = {"Andhra Pradesh", "Telangana"}


def _market_geo_index() -> tuple[dict, dict]:
    with open(_MARKET_GEO_PATH, encoding="utf-8") as f:
        rows = json.load(f)
    by_triple = {}
    by_pair: dict[tuple[str, str], list[dict]] = {}
    for r in rows:
        if r["geocode_status"] != "ok":
            continue
        key3 = (r["state"], r["district"], r["market"].strip().lower())
        by_triple[key3] = r
        by_pair.setdefault((r["state"], r["market"].strip().lower()), []).append(r)
    return by_triple, by_pair


def _district_centroids() -> dict[str, tuple[float, float]]:
    with open(_DISTRICT_GEO_PATH, encoding="utf-8") as f:
        geo_rows = json.load(f)
    coords_by_district: dict[str, list[tuple[float, float]]] = {}
    for row in geo_rows:
        if row["match_confidence"] != "matched":
            continue
        coords_by_district.setdefault(row["matched_district"], []).append(
            (row["latitude"], row["longitude"])
        )
    return {
        d: (sum(c[0] for c in coords) / len(coords), sum(c[1] for c in coords) / len(coords))
        for d, coords in coords_by_district.items()
    }


def _find_market_geo(by_triple: dict, by_pair: dict, state: str, district: str, market: str) -> dict | None:
    key3 = (state, district, market.strip().lower())
    if key3 in by_triple:
        return by_triple[key3]
    candidates = by_pair.get((state, market.strip().lower()), [])
    if len(candidates) == 1:
        return candidates[0]
    for c in candidates:
        if c["district"] == district:
            return c
    return None


def enrich() -> None:
    by_triple, by_pair = _market_geo_index()
    centroids = _district_centroids()
    logger.info(f"Loaded {len(by_triple)} geocoded AP/TG markets, {len(centroids)} district centroids")

    with open(_LAST_KNOWN_PATH, encoding="utf-8") as f:
        prices = json.load(f)

    market_matched = 0
    centroid_fallback = 0
    unmatched = []
    for entry in prices.values():
        entry.pop("pincodes", None)  # drop the old coarse district-wide list

        if entry.get("state") not in _AP_TG_STATES:
            continue

        geo = _find_market_geo(by_triple, by_pair, entry["state"], entry["district"], entry["market"])
        if geo is not None:
            entry["pincode"] = geo["pincode"]
            entry["latitude"] = geo["latitude"]
            entry["longitude"] = geo["longitude"]
            market_matched += 1
            continue

        centroid = centroids.get(entry["district"])
        if centroid is not None:
            entry["latitude"], entry["longitude"] = centroid
            entry.pop("pincode", None)
            centroid_fallback += 1
        else:
            unmatched.append((entry["state"], entry["district"], entry["market"]))

    with open(_LAST_KNOWN_PATH, "w", encoding="utf-8") as f:
        json.dump(prices, f, ensure_ascii=False, indent=2)

    logger.info(
        f"{market_matched} entries got a precise market-level pincode/lat/long, "
        f"{centroid_fallback} fell back to district centroid (no pincode), "
        f"{len(unmatched)} entries got no geo data at all"
    )
    if unmatched:
        logger.warning(f"No geo data for: {unmatched}")


if __name__ == "__main__":
    enrich()
